name: Update screenshots

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  screenshots:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Playwright
        run: |
          npm install --no-save playwright
          npx playwright install --with-deps chromium

      - name: Create screenshots
        run: |
          mkdir -p .github/assets/screenshots/light
          mkdir -p .github/assets/screenshots/dark

          node <<'EOF'
          const { chromium } = require('playwright');

          const screenshots = [
            {
              name: 'index',
              url: 'https://ynf.sh/',
            },
            {
              name: 'projects',
              url: 'https://ynf.sh/projects',
            },
            {
              name: 'posts',
              url: 'https://ynf.sh/posts',
            },
            {
              name: 'post',
              url: 'https://ynf.sh/posts/nix-secrets-a-postmodern-secrets-manager-for-nixos',
            },
          ];

          (async () => {
            const browser = await chromium.launch();

            for (const theme of ['light', 'dark']) {
              const page = await browser.newPage({
                viewport: {
                  width: 1440,
                  height: 900,
                },
                deviceScaleFactor: 1,
                colorScheme: theme,
              });

              for (const screenshot of screenshots) {
                console.log(`Screenshotting ${screenshot.url} (${theme})`);

                await page.goto(screenshot.url, {
                  waitUntil: 'networkidle',
                });

                await page.screenshot({
                  path: `.github/assets/screenshots/${theme}/${screenshot.name}.png`,
                  fullPage: false,
                });
              }

              await page.close();
            }

            await browser.close();
          })();
          EOF

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: .github/assets/screenshots/

  commit:
    needs: screenshots
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download screenshots
        uses: actions/download-artifact@v4
        with:
          name: screenshots
          path: .github/assets/screenshots

      - name: Commit screenshots
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .github/assets/screenshots/light
          git add .github/assets/screenshots/dark

          git diff --cached --quiet && exit 0

          git commit -m ".github/assets/screenshots: update"
          git push
